export enum MovieStatus {
  ANNOUNCED = "ANNOUNCED",
  PRE_PRODUCTION = "PRE_PRODUCTION",
  FILMING = "FILMING",
  POST_PRODUCTION = "POST_PRODUCTION",
  COMPLETED = "COMPLETED",
  RELEASED = "RELEASED",
  IN_THEATERS = "IN_THEATERS",
  STREAMING = "STREAMING",
  CANCELLED = "CANCELLED",
  DELAYED = "DELAYED",
  ARCHIVED = "ARCHIVED",
}