import { Language } from "@/core/movie/domain/entities/language";

export const movieLanguages: Language[] = [
  { label: "Português", value: "pt" },
  { label: "Inglês", value: "en" },
  { label: "Espanhol", value: "es" },
  { label: "Francês", value: "fr" },
  { label: "Alemão", value: "de" },
  { label: "Italiano", value: "it" },
  { label: "Japonês", value: "ja" },
  { label: "Coreano", value: "ko" },
  { label: "Chinês (Mandarim)", value: "zh" },
  { label: "Chinês (Cantonês)", value: "yue" },
  { label: "Russo", value: "ru" },
  { label: "Hindi", value: "hi" },
  { label: "Árabe", value: "ar" },
  { label: "Turco", value: "tr" },
  { label: "Sueco", value: "sv" },
  { label: "Norueguês", value: "no" },
  { label: "Dinamarquês", value: "da" },
  { label: "Finlandês", value: "fi" },
  { label: "Polonês", value: "pl" },
  { label: "Tailandês", value: "th" },
  { label: "Vietnamita", value: "vi" },
  { label: "Filipino (Tagalog)", value: "tl" },
  { label: "Indonésio", value: "id" },
  { label: "Holandês", value: "nl" },
  { label: "Grego", value: "el" },
  { label: "Hebraico", value: "he" },
  { label: "Tcheco", value: "cs" },
  { label: "Húngaro", value: "hu" },
  { label: "Romeno", value: "ro" },
  { label: "Ucraniano", value: "uk" },
  { label: "Bengalês", value: "bn" },
  { label: "Persa (Farsi)", value: "fa" },
  { label: "Malaio", value: "ms" },
  { label: "Islandês", value: "is" },
  { label: "Eslovaco", value: "sk" },
  { label: "Esloveno", value: "sl" },
  { label: "Croata", value: "hr" },
  { label: "Sérvio", value: "sr" },
  { label: "Búlgaro", value: "bg" },
  { label: "Georgiano", value: "ka" },
  { label: "Armênio", value: "hy" },
  { label: "Latim", value: "la" },
  { label: "Swahili", value: "sw" },
  { label: "Zulu", value: "zu" },
  { label: "Afrikaans", value: "af" },
  { label: "Catalão", value: "ca" },
  { label: "Basco", value: "eu" },
  { label: "Tamil", value: "ta" },
  { label: "Telugu", value: "te" },
  { label: "Malaiala (Malayalam)", value: "ml" },
];